services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: bluetile
      POSTGRES_PASSWORD: bluetile
      POSTGRES_DB: bluetile_development
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
